[package]
name = "git-lfs-rust-cgi-server"
version = "0.1.0"
edition = "2024"

[features]
log = []

[dependencies]
cgi = "0.8.0"
lazy_static = "1.5.0"
log = "0.4.29"
process_path = "0.1.4"
serde_json = "1.0.145"
simple-logging = "2.0.2"
url = "2.5.7"
